
# The singles
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert                        adder
#/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/insert                        adder

#/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/insert                        merger
#/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/merger/addInput  adder/Singles_LYSO

/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert                        readout
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/readout/setDepth              1

/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert                        energyResolution
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyResolution/fwhm        0.26
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyResolution/energyOfReference 511. keV

/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert                        energyFraming
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyFraming/setMin      430.0 keV
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyFraming/setMax            645.0 keV


# Coincidence sorter
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setInputCollection Singles_LYSO
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setWindow          5 ns
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setOffset 0. ns
/gate/digitizerMgr/CoincidenceSorter/Coincidences/MultiplesPolicy    takeWinnerOfGoods

/gate/digitizerMgr/name                            delay
/gate/digitizerMgr/insert                          CoincidenceSorter
/gate/digitizerMgr/CoincidenceSorter/delay/setInputCollection Singles_LYSO
/gate/digitizerMgr/CoincidenceSorter/delay/setWindow                 4.7 ns
/gate/digitizerMgr/CoincidenceSorter/delay/setOffset                 75 ns
#/gate/digitizerMgr/delay/MultiplesPolicy          takeWinnerOfGoods


