
#	CYLINDRICAL
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 cm
/gate/cylindricalPET/geometry/setRmax 52.0 cm
/gate/cylindricalPET/geometry/setRmin 0 cm
/gate/cylindricalPET/geometry/setHeight 194 cm
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setColor white

#	HEAD (rsector)
/gate/cylindricalPET/daughters/name head
/gate/cylindricalPET/daughters/insert box
/gate/head/placement/setTranslation 0.0 0.0 0.0 cm
/gate/head/geometry/setXLength  25 cm
/gate/head/geometry/setYLength 12 cm
/gate/head/geometry/setZLength 20 cm
/gate/head/setMaterial Air
/gate/head/vis/setVisible 0


#	MODULE
/gate/head/daughters/name module
/gate/head/daughters/insert box
/gate/module/placement/setTranslation 2.5 0.0 0.0 cm
/gate/module/geometry/setXLength 23.81 cm
/gate/module/geometry/setYLength 9.93 cm
/gate/module/geometry/setZLength 1.9 cm
/gate/module/setMaterial Air
/gate/module/vis/setVisible 0


#	BLOCK
/gate/module/daughters/name block
/gate/module/daughters/insert box
/gate/block/placement/setTranslation 0.0 0.0 0.0 cm
/gate/block/geometry/setXLength 17.01 mm
/gate/block/geometry/setYLength 19.86 mm
/gate/block/geometry/setZLength 18.10 mm
/gate/block/setMaterial Air
/gate/block/vis/setVisible 0

#	C R Y S T A L
/gate/block/daughters/name crystal
/gate/block/daughters/insert box
/gate/crystal/placement/setTranslation 0.0 0.0 0.0 cm
/gate/crystal/geometry/setXLength 2.76 mm
/gate/crystal/geometry/setYLength 2.76 mm
/gate/crystal/geometry/setZLength 18.10 mm
/gate/crystal/setMaterial Air
/gate/crystal/vis/setVisible 0


#	LYSO layer
/gate/crystal/daughters/name LYSO
/gate/crystal/daughters/insert box
/gate/LYSO/placement/setTranslation 0.0 0.0 0.0 cm
/gate/LYSO/geometry/setXLength 2.76 mm
/gate/LYSO/geometry/setYLength 2.76 mm
/gate/LYSO/geometry/setZLength 18.10 mm
/gate/LYSO/setMaterial LYSO
/gate/LYSO/vis/setColor green


#	R E P E A T    C R Y S T A L
/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 6
/gate/crystal/cubicArray/setRepeatNumberY 7
/gate/crystal/cubicArray/setRepeatNumberZ 1
/gate/crystal/cubicArray/setRepeatVector 2.85 2.85 0.0 mm


#	R E P E A T    BLOCK
/gate/block/repeaters/insert cubicArray
/gate/block/cubicArray/setRepeatNumberX 14
/gate/block/cubicArray/setRepeatNumberY 5
/gate/block/cubicArray/setRepeatNumberZ 1
/gate/block/cubicArray/setRepeatVector 17.00 19.85 0.0 mm


#	R E P E A T MODULE
#/gate/module/repeaters/insert cubicArray
#/gate/module/cubicArray/setRepeatNumberX 1
#/gate/module/cubicArray/setRepeatNumberY 1
#/gate/module/cubicArray/setRepeatNumberZ 8
#/gate/module/cubicArray/setRepeatVector 0.0 0.0 3.0 cm
/gate/module/placement/setRotationAxis 0 1 0 90 deg

#	R E P E A T HEAD
/gate/head/repeaters/insert ring
/gate/head/ring/setRepeatNumber 24
#/gate/head/ring/setRadius 39.3 cm               # uEXPLORER ring radius

/gate/head/repeaters/insert linear
/gate/head/linear/setRepeatNumber 8
/gate/head/linear/setRepeatVector 0.0 0.0 24.25 cm   # 8 stacks over ~194 cm AFOV


#/gate/cylindricalPET/moves/insert orbiting
#/gate/cylindricalPET/orbiting/setSpeed .1875 deg/s
#/gate/cylindricalPET/orbiting/setPoint1 0 0 0 cm
#/gate/cylindricalPET/orbiting/setPoint2 0 0 1 cm

#	A T T A C H    S Y S T E M 
/gate/systems/cylindricalPET/rsector/attach head
/gate/systems/cylindricalPET/module/attach module
/gate/systems/cylindricalPET/submodule/attach block
/gate/systems/cylindricalPET/crystal/attach crystal
/gate/systems/cylindricalPET/layer0/attach LYSO

#	A T T A C H    C R Y S T A L  SD

/gate/LYSO/attachCrystalSD

#/gate/geometry/enableAutoOverlapCheck 1
/gate/systems/cylindricalPET/describe

/gate/module/placement/setRotationAxis 0 1 0 90 deg

