##########################################################
# Point Source 5: 1/8 AFOV (z=24.25cm), r=10cm
# Activity: 300 kBq
##########################################################

/gate/source/addSource F18_point_5
/gate/source/F18_point_5/setActivity 300000 becquerel

/gate/source/F18_point_5/gps/particle e+
/gate/source/F18_point_5/setForcedUnstableFlag true
/gate/source/F18_point_5/setForcedHalfLife 6586.2 s
/gate/source/F18_point_5/gps/energytype Fluor18

/gate/source/F18_point_5/gps/type Volume
/gate/source/F18_point_5/gps/shape Sphere
/gate/source/F18_point_5/gps/radius 0.025 cm
/gate/source/F18_point_5/gps/centre 10.0 0.0 24.25 cm
/gate/source/F18_point_5/gps/angtype iso

/gate/source/F18_point_5/gps/confine point_source_5

/gate/source/list
