##########################################################
# Point Source 4: 1/8 AFOV (z=24.25cm), r=1cm
# Activity: 300 kBq
##########################################################

/gate/source/addSource F18_point_4
/gate/source/F18_point_4/setActivity 300000 becquerel

/gate/source/F18_point_4/gps/particle e+
/gate/source/F18_point_4/setForcedUnstableFlag true
/gate/source/F18_point_4/setForcedHalfLife 6586.2 s
/gate/source/F18_point_4/gps/energytype Fluor18

/gate/source/F18_point_4/gps/type Volume
/gate/source/F18_point_4/gps/shape Sphere
/gate/source/F18_point_4/gps/radius 0.025 cm
/gate/source/F18_point_4/gps/centre 1.0 0.0 24.25 cm
/gate/source/F18_point_4/gps/angtype iso

/gate/source/F18_point_4/gps/confine point_source_4

/gate/source/list
